name: todolist_app # The name of your Flutter project, as provided
description: "A new Flutter project." # Description as provided by the user
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1 # Major.Minor.Patch+BuildNumber

environment:
  sdk: ^3.8.0 # Updated Dart SDK version as per your input

dependencies:
  flutter:
    sdk: flutter # Core Flutter framework

  cupertino_icons: ^1.0.8 # Updated iOS-style icons version as per your input
  flutter_svg: ^2.0.10+1 # Essential for rendering SVG assets (like your app logo, icons)
  intl: ^0.19.0 # Provides internationalization and localization capabilities, useful for date/time formatting
  path_provider: ^2.1.3 # Required for getting platform-specific paths for local storage (e.g., for ObjectBox)
  objectbox: ^2.5.0 # For local data persistence, as indicated by your TODO comment.
  objectbox_sync_flutter_libs: ^2.5.0 # Required for ObjectBox in Flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter # For writing unit and widget tests
  flutter_lints: ^5.0.0 # Updated lints package version as per your input
  build_runner: ^2.4.9 # Code generation tool, often used with ObjectBox
  objectbox_generator: ^2.5.0 # ObjectBox code generator

# The "flutter" section is used to specify assets and fonts.
flutter:
  uses-material-design: true # Enables Material Design in your app

  # To add assets to your application, add an assets section below.
  # Assets are files that are bundled with your application.
  assets:
    - assets/trans_logo.svg # Individual asset paths as provided by you
    - assets/plus.svg
    - assets/back.svg
    - assets/hamburger.svg
    - assets/filter.svg
    - assets/bell_white.svg
    - assets/cross.svg

  # To add custom fonts to your application, add a fonts section below.
  fonts:
    - family: Inter # The font family name you'll use in your app
     